config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users
  root to: 'listings#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show index]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cancancan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav'%>
    <% if notice%>
    <p class="notice alert alert-primary"><%= notice %></p>
    <%end%>
    <% if alert%>
    <p class="alert alert-danger"><%= alert %></p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>
      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3">
    <%= form.label :title, class:'form-label' %>
    <%= form.text_field :title, class:'form-text'%>
  </div>
  <div class="field mb-3">
    <%= form.label :description, class:'form-label'%>
    <%= form.text_area :description, class:'form-text'%>
  </div>
  <div class="actions ">
    <%= form.submit class:'btn btn-primary' %>
    <%= link_to 'Back', listings_path, class:'back-button btn btn-secondary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<div class="container">
<div class="d-flex justify-content-center flex-column align-items-center">
<%= render 'form', listing: @listing %>
<div class="actions">
<%= link_to 'Show', @listing, class:'btn btn-secondary m-2' %>
</div>
</div>
</div>

app/views/listings/index.html.erb
<h1 class='mt-5'>Listings</h1>
<div class="container">
  <div class="flex">
    <% @listings.each do |listing| %>
      <div class="card m-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= listing.title %></h5>
          <p class="card-text"><%= listing.description %></p>
          <%= link_to 'Show', listing, class:'btn btn-primary'%>
          <%if user_signed_in? && current_user == listing.user%>
            <%= link_to 'Edit', edit_listing_path(listing), class:'btn btn-warning' %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<div class="container">
<div class="d-flex justify-content-center flex-column align-items-center">
<%= render 'form', listing: @listing %>

</div>
</div>

app/views/listings/show.html.erb
<h2>
  <%= @listing.title %>
</h2>
<p class='text-center'>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>
<div class="text-center">
  <%= link_to 'Edit', edit_listing_path(@listing), class:'btn btn-warning' if current_user && current_user == @listing.user %> 
  <%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' if current_user && current_user == @listing.user%>
  <%= link_to 'Back', listings_path, class:'btn btn-secondary' %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Great Online Store', root_path, class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav container-fluid">
        <li class='nav-item'>
          <%= link_to 'New Listing', new_listing_path, class:'nav-link'%>
        </li>
        <% if user_signed_in? %>
          <li class='nav-item d-flex'>
            <%= link_to destroy_user_session_path, method: :delete, class:' nav-link' do %>
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="sign-out-alt" class="svg-inline--fa fa-sign-out-alt fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M497 273L329 441c-15 15-41 4.5-41-17v-96H152c-13.3 0-24-10.7-24-24v-96c0-13.3 10.7-24 24-24h136V88c0-21.4 25.9-32 41-17l168 168c9.3 9.4 9.3 24.6 0 34zM192 436v-40c0-6.6-5.4-12-12-12H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h84c6.6 0 12-5.4 12-12V76c0-6.6-5.4-12-12-12H96c-53 0-96 43-96 96v192c0 53 43 96 96 96h84c6.6 0 12-5.4 12-12z"></path></svg>
              <span class="link-text">Log Out</span>
            <% end %>
          </li>
        <% else %>
          <li class='nav-item d-flex'>
            <%= link_to new_user_session_path, class:' nav-link' do %>
              <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="sign-in-alt" class="svg-inline--fa fa-sign-in-alt fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M416 448h-84c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h84c17.7 0 32-14.3 32-32V160c0-17.7-14.3-32-32-32h-84c-6.6 0-12-5.4-12-12V76c0-6.6 5.4-12 12-12h84c53 0 96 43 96 96v192c0 53-43 96-96 96zm-47-201L201 79c-15-15-41-4.5-41 17v96H24c-13.3 0-24 10.7-24 24v96c0 13.3 10.7 24 24 24h136v96c0 21.5 26 32 41 17l168-168c9.3-9.4 9.3-24.6 0-34z"></path></svg>
              <span class="link-text">Log In</span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>